### ISSUE TITLE
BGE M3

### ISSUE THREAD

**Issue by sailfish009** [MoritzLaurer/zeroshot-classifier#3]
Can I use Tokenizer BGE M3 as part of fine-tuning for pre-trained models?

https://huggingface.co/BAAI/bge-m3

https://arxiv.org/html/2402.03216v3

**Comment by MoritzLaurer** [comment]
Not quite sure if I understand your question. You always need to use the tokenizer that fits to the specific model you are using. You cannot use the BGE tokenizer with e.g. a deberta model. But you can fine-tune a BGE-M3 model for 0-shot. 
Btw: I'm currently fine-tuning BGE-M3 for a new 0-shot model, will communicate about it in the coming days :)

**Comment by skunkwerk** [comment]
Hey Moritz, thanks for this great work.  I saw you released the bge m3 model on Huggingface; is the repo updated with the code for that training?

**Comment by MoritzLaurer** [comment]
yes, the repo (this [script here](https://github.com/MoritzLaurer/zeroshot-classifier/blob/main/v2_synthetic_data/synth_train_eval.ipynb)) should work with the m3 model (or any encoder-only model). You only need to change the `model_name` variable to the HF id of an encoder-only model (BERT, RoBERTa, DeBERTa, MPNET etc. - but not decoder models like Llama)
